#!/usr/bin/env node
// v0.5.53 — Bake the operator's cloud transcription keys into the
// renderer at build/dev time.
//
// WHY THIS EXISTS
// ----------------
// Earlier versions tried to inline the keys via `next.config.ts`'s
// `env` block, reading them from `process.env` at next-config eval
// time. That worked in CI but broke in two real-world cases:
//   1. Operator unzips source on a fresh Windows PC -> no env vars
//      set -> next builds with empty NEXT_PUBLIC_* vars -> the
//      packaged .exe ships with EMPTY keys -> end-users see
//      "No OpenAI key configured" and the app is dead on arrival.
//   2. Replit dev launches before secrets propagate to the next
//      process -> same empty-bake problem in dev.
//
// HOW IT WORKS NOW
// -----------------
// This script writes a TS source file (`src/lib/keys.baked.ts`)
// containing the literal key values as plain string constants. The
// renderer imports those constants directly. Because they are plain
// source code (not env-var references), Webpack/Turbopack inline
// them into the client bundle with 100% reliability — no env-var
// timing issues, no build-vs-runtime mismatch.
//
// SECRET-LEAK MITIGATION
// ----------------------
// `src/lib/keys.baked.ts` is gitignored, so the literal keys are
// NEVER pushed to GitHub (where OpenAI's secret-scanner would auto-
// revoke them within minutes). The source-ZIP packager explicitly
// includes the file, so when the operator unzips on their build
// machine the keys are already present and BUILD.bat just works
// without asking for any input.
//
// FALLBACK CHAIN
// --------------
// 1. process.env.SCRIPTURELIVE_OPENAI_KEY (operator override)
// 2. process.env.OPENAI_API_KEY            (Replit secret name)
// 3. existing value already in keys.baked.ts (preserve previous)
// 4. empty string                          (only on first run with
//                                            no env vars at all)

import fs from 'node:fs'
import path from 'node:path'
import url from 'node:url'

const __filename = url.fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const TARGET = path.join(__dirname, '..', 'src', 'lib', 'keys.baked.ts')

function pickKey(...names) {
  for (const n of names) {
    const v = (process.env[n] || '').trim()
    if (v) return v
  }
  return ''
}

// Extract any keys that may already be baked into the existing file
// so that running this script with empty env vars (e.g. operator
// rebuilding) does NOT clobber a previously-injected value.
function readExisting() {
  try {
    const src = fs.readFileSync(TARGET, 'utf8')
    const o = src.match(/BAKED_OPENAI_KEY\s*=\s*"([^"]*)"/)
    const d = src.match(/BAKED_DEEPGRAM_KEY\s*=\s*"([^"]*)"/)
    return { openai: (o && o[1]) || '', deepgram: (d && d[1]) || '' }
  } catch {
    return { openai: '', deepgram: '' }
  }
}

const existing = readExisting()
const openai = pickKey('SCRIPTURELIVE_OPENAI_KEY', 'OPENAI_API_KEY') || existing.openai
const deepgram = pickKey('SCRIPTURELIVE_DEEPGRAM_KEY', 'DEEPGRAM_API_KEY') || existing.deepgram

const banner =
  '// AUTO-GENERATED by scripts/inject-keys.mjs — DO NOT EDIT BY HAND.\n' +
  '// This file is gitignored. The literal key values are baked into the\n' +
  '// renderer bundle so the packaged .exe ships with working\n' +
  '// transcription out of the box, no operator setup required.\n' +
  '// To override at runtime, paste new values in Admin → Cloud Keys.\n\n'

const body =
  `export const BAKED_OPENAI_KEY = ${JSON.stringify(openai)};\n` +
  `export const BAKED_DEEPGRAM_KEY = ${JSON.stringify(deepgram)};\n`

fs.mkdirSync(path.dirname(TARGET), { recursive: true })
fs.writeFileSync(TARGET, banner + body, 'utf8')

// Print STATUS only — never the actual key values.
const mask = (k) => (k ? `${k.length} chars` : 'EMPTY')
console.log(`[inject-keys] OPENAI=${mask(openai)} DEEPGRAM=${mask(deepgram)} -> ${path.relative(process.cwd(), TARGET)}`)
