#!/usr/bin/env node
// v0.5.54 — Bake the operator's credentials into the build at
// dev/build time so the packaged .exe ships with everything it
// needs out of the box. Two distinct surfaces are baked:
//
//   RENDERER (browser) — `src/lib/keys.baked.ts`
//     DEEPGRAM_API_KEY
//     Used by the renderer's transcription hooks.
//
//   v0.7.20 — OPENAI_API_KEY removal: the renderer no longer
//   bakes an OpenAI key. v0.7.19 already cut OpenAI/Whisper from
//   ENGINE_CHAIN (Deepgram-only transcription) and the operator
//   asked to stop using OpenAI entirely. The renderer-side
//   semantic matcher already gracefully no-ops when no key is
//   present, so dropping the bake is safe. The Replit secret
//   has also been deleted so no plaintext key can leak through
//   the build pipeline again.
//
//   SERVER (Node)     — `src/lib/baked-credentials.ts`
//     MAIL_HOST, MAIL_USER, MAIL_PASS, MAIL_FROM, MAIL_PORT,
//     MAIL_SECURE, SMS_API_KEY, SMS_SENDER, SMS_SANDBOX
//     Used by the licensing notifications + SMS modules. v0.5.53
//     left these reading process.env only, which broke as soon as
//     the operator launched the .exe (which has no env vars set
//     by default) — the admin panel said "SMTP not configured"
//     and customers received no activation emails or SMS.
//
// FALLBACK CHAIN
// --------------
// At RUNTIME the resolvers prefer env-vars over baked values, so:
//   1. process.env.<NAME>            (always wins if set)
//   2. baked literal from this script
//   3. empty string                  (caller surfaces "missing")
//
// SECRET-LEAK MITIGATION
// ----------------------
// Both generated files are .gitignored. The source-ZIP packager
// includes them explicitly so the operator's BUILD.bat finds the
// keys ready to bake. GitHub never sees them, so OpenAI / Deepgram
// secret-scanners do not auto-revoke.
//
// PRESERVATION ON RE-RUN
// ----------------------
// If the operator runs BUILD.bat with no env vars set, the script
// re-reads the literal values already in the generated files and
// keeps them, so a rebuild never clobbers the keys we shipped.

import fs from 'node:fs'
import path from 'node:path'
import url from 'node:url'

const __filename = url.fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const RENDERER_TARGET = path.join(__dirname, '..', 'src', 'lib', 'keys.baked.ts')
const SERVER_TARGET   = path.join(__dirname, '..', 'src', 'lib', 'baked-credentials.ts')

// v0.5.54 hardening — operators occasionally paste a Replit
// "Set this secret" placeholder where the value equals the literal
// variable name (e.g. MAIL_PORT="MAIL_PORT"). Treat such values as
// unset so the consumer falls back to its hard-coded default
// (notifications.ts uses 587 when MAIL_PORT is empty).
function pickEnv(...names) {
  for (const n of names) {
    const v = (process.env[n] || '').trim()
    if (!v) continue
    if (v === n) continue                                  // placeholder: value === name
    if (n === 'MAIL_PORT' && !/^\d{1,5}$/.test(v)) continue // MAIL_PORT must be a positive integer
    return v
  }
  return ''
}

// Pull literal value already baked under a particular const name so
// re-runs with empty env vars don't clobber a previously-injected one.
// v0.5.54 hardening — match a JSON-encoded string literal greedily
// (handling embedded escaped quotes / backslashes) and JSON.parse
// the captured literal so values like passwords containing " or \
// round-trip cleanly. Also re-applies the same placeholder /
// numeric-port validation as pickEnv() so a previously-baked bad
// value (e.g. MAIL_PORT="MAIL_PORT" from a v0.5.54.0 build before
// these guards existed) is now self-healed instead of preserved.
function readBaked(target, constName, envName = '') {
  try {
    const src = fs.readFileSync(target, 'utf8')
    const re = new RegExp(constName + '\\s*=\\s*("(?:[^"\\\\]|\\\\.)*")')
    const m = src.match(re)
    if (!m) return ''
    let v
    try { v = JSON.parse(m[1]) } catch { return '' }
    if (!v) return ''
    if (envName && v === envName) return ''                              // placeholder
    if (envName === 'MAIL_PORT' && !/^\d{1,5}$/.test(v)) return ''       // non-numeric port
    return v
  } catch {
    return ''
  }
}

function mask(k) { return k ? `${k.length} chars` : 'EMPTY' }

// ── Renderer keys (browser-side) ───────────────────────────────────
const deepgram = pickEnv('SCRIPTURELIVE_DEEPGRAM_KEY', 'DEEPGRAM_API_KEY') || readBaked(RENDERER_TARGET, 'BAKED_DEEPGRAM_KEY')

const rendererBanner =
  '// AUTO-GENERATED by scripts/inject-keys.mjs — DO NOT EDIT BY HAND.\n' +
  '// This file is gitignored. The literal key values are baked into\n' +
  '// the renderer bundle so the packaged .exe ships with working\n' +
  '// transcription out of the box, no operator setup required.\n' +
  '// v0.7.20 — OPENAI_API_KEY removed from RENDERER bake.\n' +
  '// v0.7.25 — OpenAI bake restored, but on the SERVER side only\n' +
  '//   (see baked-credentials.ts) so the embedding key never\n' +
  '//   reaches the renderer bundle. The semantic matcher runs in\n' +
  '//   the Next.js API route /api/scripture/semantic-match.\n\n'

const rendererBody =
  `export const BAKED_DEEPGRAM_KEY = ${JSON.stringify(deepgram)};\n`

fs.mkdirSync(path.dirname(RENDERER_TARGET), { recursive: true })
fs.writeFileSync(RENDERER_TARGET, rendererBanner + rendererBody, 'utf8')

// ── Server credentials (Node-side) ─────────────────────────────────
//
// v0.7.19 — ADMIN_PASSWORD baking. Operator reported that the admin
// password they save on PC1 (e.g. "1234") doesn't carry over to
// PC2 — every fresh install fell back to the legacy "admin" default.
// Solution: bake the operator-chosen password into the .exe at
// build time so every PC running the same build shares the same
// default. Per-PC overrides via Admin → Settings still win, so an
// operator can still pick a different local password on one PC if
// they want. Resolution order at runtime (in admin-auth.ts):
//   1. license.json adminPassword (per-PC operator override)
//   2. process.env.SCRIPTURELIVE_ADMIN_PASSWORD (env override)
//   3. BAKED_ADMIN_PASSWORD (this value, shipped in the .exe)
//   4. legacy "admin" default (only if literally nothing is set)
// readBaked envName='ADMIN_PASSWORD' engages the placeholder guard
// so an accidentally-pasted literal "ADMIN_PASSWORD" from a secret-
// manager template is self-healed on the next build instead of
// being preserved as the actual password.
const adminPwd   = pickEnv('SCRIPTURELIVE_ADMIN_PASSWORD', 'ADMIN_PASSWORD')
                  || readBaked(SERVER_TARGET, 'BAKED_ADMIN_PASSWORD', 'ADMIN_PASSWORD')
const mailHost   = pickEnv('MAIL_HOST')   || readBaked(SERVER_TARGET, 'BAKED_MAIL_HOST',   'MAIL_HOST')
const mailUser   = pickEnv('MAIL_USER')   || readBaked(SERVER_TARGET, 'BAKED_MAIL_USER',   'MAIL_USER')
const mailPass   = pickEnv('MAIL_PASS')   || readBaked(SERVER_TARGET, 'BAKED_MAIL_PASS',   'MAIL_PASS')
const mailFrom   = pickEnv('MAIL_FROM')   || readBaked(SERVER_TARGET, 'BAKED_MAIL_FROM',   'MAIL_FROM')
const mailPort   = pickEnv('MAIL_PORT')   || readBaked(SERVER_TARGET, 'BAKED_MAIL_PORT',   'MAIL_PORT')
const mailSecure = pickEnv('MAIL_SECURE') || readBaked(SERVER_TARGET, 'BAKED_MAIL_SECURE', 'MAIL_SECURE')
const smsApiKey  = pickEnv('SMS_API_KEY') || readBaked(SERVER_TARGET, 'BAKED_SMS_API_KEY', 'SMS_API_KEY')
const smsSender  = pickEnv('SMS_SENDER')  || readBaked(SERVER_TARGET, 'BAKED_SMS_SENDER',  'SMS_SENDER')
const smsSandbox = pickEnv('SMS_SANDBOX') || readBaked(SERVER_TARGET, 'BAKED_SMS_SANDBOX', 'SMS_SANDBOX')

// v0.7.25 — OpenAI key bake (server-only). Reverses the v0.7.20
// removal because v0.7.23 introduced AI Verse Search and v0.7.24
// fixed AI Scripture Detection — both rely on OpenAI embeddings.
// Operator confirmed: they don't want every church having to
// paste a key into the Admin modal. Bake the operator's key into
// the installer so AI features work out of the box on every
// PC, exactly like Deepgram does.
//
// SECURITY/COST NOTE
// ------------------
// Same trust model as Deepgram: every operator's installer hits
// OpenAI on the build-owner's account. The semantic matcher uses
// text-embedding-3-small at ~$0.02 per 1M tokens, and most voice
// commands are under 20 tokens — usage is negligible. The key
// stays out of the renderer bundle (server-only), so end users
// can't read it from devtools.
const openai = pickEnv('OPENAI_API_KEY') || readBaked(SERVER_TARGET, 'BAKED_OPENAI_KEY', 'OPENAI_API_KEY')

const serverBanner =
  '// AUTO-GENERATED by scripts/inject-keys.mjs — DO NOT EDIT BY HAND.\n' +
  '// Server-side baked credentials. Imported by\n' +
  '//   src/lib/licensing/notifications.ts (SMTP)\n' +
  '//   src/lib/licensing/sms.ts          (Arkesel)\n' +
  '//   src/app/api/license/admin/list/route.ts (panel banner)\n' +
  '//   src/instrumentation.ts            (startup test email)\n' +
  '// Each consumer prefers process.env when present and falls back\n' +
  '// to these literal values, so the .exe works on a fresh PC even\n' +
  '// without the operator pasting any secrets into the system\n' +
  '// environment. Gitignored — never reaches GitHub.\n\n'

const serverBody =
  `export const BAKED_MAIL_HOST    = ${JSON.stringify(mailHost)};\n` +
  `export const BAKED_MAIL_USER    = ${JSON.stringify(mailUser)};\n` +
  `export const BAKED_MAIL_PASS    = ${JSON.stringify(mailPass)};\n` +
  `export const BAKED_MAIL_FROM    = ${JSON.stringify(mailFrom)};\n` +
  `export const BAKED_MAIL_PORT    = ${JSON.stringify(mailPort)};\n` +
  `export const BAKED_MAIL_SECURE  = ${JSON.stringify(mailSecure)};\n` +
  `export const BAKED_SMS_API_KEY  = ${JSON.stringify(smsApiKey)};\n` +
  `export const BAKED_SMS_SENDER   = ${JSON.stringify(smsSender)};\n` +
  `export const BAKED_SMS_SANDBOX  = ${JSON.stringify(smsSandbox)};\n` +
  `export const BAKED_ADMIN_PASSWORD = ${JSON.stringify(adminPwd)};\n` +
  `export const BAKED_OPENAI_KEY   = ${JSON.stringify(openai)};\n` +
  '\n' +
  'function pick(envValue: string | undefined, baked: string): string {\n' +
  '  const e = (envValue || "").trim();\n' +
  '  if (e) return e;\n' +
  '  return baked || "";\n' +
  '}\n' +
  '\n' +
  'export const getMailHost   = () => pick(process.env.MAIL_HOST,   BAKED_MAIL_HOST);\n' +
  'export const getMailUser   = () => pick(process.env.MAIL_USER,   BAKED_MAIL_USER);\n' +
  'export const getMailPass   = () => pick(process.env.MAIL_PASS,   BAKED_MAIL_PASS);\n' +
  'export const getMailFrom   = () => pick(process.env.MAIL_FROM,   BAKED_MAIL_FROM);\n' +
  'export const getMailPort   = () => pick(process.env.MAIL_PORT,   BAKED_MAIL_PORT);\n' +
  'export const getMailSecure = () => pick(process.env.MAIL_SECURE, BAKED_MAIL_SECURE);\n' +
  'export const getSmsApiKey  = () => pick(process.env.SMS_API_KEY, BAKED_SMS_API_KEY);\n' +
  'export const getSmsSender  = () => pick(process.env.SMS_SENDER,  BAKED_SMS_SENDER);\n' +
  'export const getSmsSandbox = () => pick(process.env.SMS_SANDBOX, BAKED_SMS_SANDBOX);\n' +
  '\n' +
  '/** v0.7.19 — Returns the build-baked default admin password,\n' +
  ' *  or empty string if the operator never set one. Honoured by\n' +
  ' *  resolveAdminPassword() in licensing/admin-auth.ts as a\n' +
  ' *  fallback BEFORE the legacy hard-coded "admin" default, so\n' +
  ' *  every install of the same .exe build shares the same default\n' +
  ' *  password. Per-PC overrides saved into license.json still\n' +
  ' *  win — operators can pick a different local password on one\n' +
  ' *  PC without affecting any other install. */\n' +
  'export const getBakedAdminPassword = () => BAKED_ADMIN_PASSWORD || "";\n' +
  '\n' +
  '/** v0.7.25 — Returns the build-baked OpenAI API key, or empty\n' +
  ' *  string if the build was produced with no OPENAI_API_KEY env\n' +
  ' *  var (and no key preserved from a prior bake). The semantic\n' +
  ' *  matcher in src/lib/ai/semantic-matcher.ts honours this as a\n' +
  ' *  fallback AFTER process.env and the per-PC license override,\n' +
  ' *  so every install of the same .exe build picks up the bundled\n' +
  ' *  key automatically — operators never need to paste a key into\n' +
  ' *  the Admin modal. Per-PC license overrides still win, so a\n' +
  ' *  church can supply their own OpenAI key on one PC if they want\n' +
  ' *  to bill against their own account. */\n' +
  'export const getOpenAIKey = () => pick(process.env.OPENAI_API_KEY, BAKED_OPENAI_KEY);\n' +
  '\n' +
  '/** Diagnostic — used by the admin panel to render the green/amber\n' +
  ' *  delivery banner. SMTP needs host + user + pass at minimum;\n' +
  ' *  MAIL_FROM falls back to MAIL_USER inside the sender. */\n' +
  'export function detectNotificationDelivery() {\n' +
  '  const smtpConfigured = !!(getMailHost() && getMailUser() && getMailPass());\n' +
  '  const smsConfigured  = !!getSmsApiKey();\n' +
  '  return { smtpConfigured, smsConfigured };\n' +
  '}\n'

fs.writeFileSync(SERVER_TARGET, serverBanner + serverBody, 'utf8')

console.log(
  `[inject-keys] renderer: DEEPGRAM=${mask(deepgram)}\n` +
  `[inject-keys] server:   MAIL_HOST=${mailHost ? 'SET' : 'EMPTY'} MAIL_USER=${mailUser ? 'SET' : 'EMPTY'} MAIL_PASS=${mask(mailPass)} MAIL_FROM=${mailFrom ? 'SET' : 'EMPTY'} SMS_API_KEY=${mask(smsApiKey)} SMS_SENDER=${smsSender ? 'SET' : 'EMPTY'} ADMIN_PASSWORD=${adminPwd ? `SET (${adminPwd.length} chars)` : 'EMPTY (default "admin" will apply)'} OPENAI=${mask(openai)}`
)
