uploads = []
generated = []

[[outputs]]
id = "9E80LzCXA9PVsyKh_KgUO"
uri = "file://exports/release-desktop-fixed.zip"
type = "unspecified"
title = "release-desktop.yml (Windows-only)"

[[outputs]]
id = "6gK736AC5-m61L84mY9ho"
uri = "file://exports/ScriptureLive-AI-v0.5.5-source.zip"
type = "unspecified"
title = "ScriptureLive AI v0.5.5 — Source"
