// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scripturelive-hotfix11/FrameBridge.tsx": () => import("../components/mockups/scripturelive-hotfix11/FrameBridge.tsx"),
  "./components/mockups/scripturelive-hotfix11/LtReferenceCap.tsx": () => import("../components/mockups/scripturelive-hotfix11/LtReferenceCap.tsx"),
  "./components/mockups/scripturelive-hotfix11/LtSliderFix.tsx": () => import("../components/mockups/scripturelive-hotfix11/LtSliderFix.tsx"),
  "./components/mockups/brightness/Current.tsx": () => import("../components/mockups/brightness/Current.tsx"),
  "./components/mockups/brightness/Max.tsx": () => import("../components/mockups/brightness/Max.tsx"),
  "./components/mockups/brightness/Mid.tsx": () => import("../components/mockups/brightness/Mid.tsx")
};
