// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scripturelive-hotfix11/FrameBridge.tsx": () => import("../components/mockups/scripturelive-hotfix11/FrameBridge.tsx"),
  "./components/mockups/scripturelive-hotfix11/LtReferenceCap.tsx": () => import("../components/mockups/scripturelive-hotfix11/LtReferenceCap.tsx"),
  "./components/mockups/scripturelive-hotfix11/LtSliderFix.tsx": () => import("../components/mockups/scripturelive-hotfix11/LtSliderFix.tsx")
};
