// AUTO-GENERATED by scripts/inject-keys.mjs — DO NOT EDIT BY HAND.
// Server-side baked credentials. Imported by
//   src/lib/licensing/notifications.ts (SMTP)
//   src/lib/licensing/sms.ts          (Arkesel)
//   src/app/api/license/admin/list/route.ts (panel banner)
//   src/instrumentation.ts            (startup test email)
// Each consumer prefers process.env when present and falls back
// to these literal values, so the .exe works on a fresh PC even
// without the operator pasting any secrets into the system
// environment. Gitignored — never reaches GitHub.

export const BAKED_MAIL_HOST   = "smtp.gmail.com";
export const BAKED_MAIL_USER   = "nanvilow@gmail.com";
export const BAKED_MAIL_PASS   = "fzxk mdfy cgcx uwop";
export const BAKED_MAIL_FROM   = "ScriptureLive AI nanvilow@gmail.com";
export const BAKED_MAIL_PORT   = "";
export const BAKED_MAIL_SECURE = "";
export const BAKED_SMS_API_KEY = "EgBTnNok3AKpJCKluIhv1xnRd";
export const BAKED_SMS_SENDER  = "WassMedia";
export const BAKED_SMS_SANDBOX = "";

function pick(envValue: string | undefined, baked: string): string {
  const e = (envValue || "").trim();
  if (e) return e;
  return baked || "";
}

export const getMailHost   = () => pick(process.env.MAIL_HOST,   BAKED_MAIL_HOST);
export const getMailUser   = () => pick(process.env.MAIL_USER,   BAKED_MAIL_USER);
export const getMailPass   = () => pick(process.env.MAIL_PASS,   BAKED_MAIL_PASS);
export const getMailFrom   = () => pick(process.env.MAIL_FROM,   BAKED_MAIL_FROM);
export const getMailPort   = () => pick(process.env.MAIL_PORT,   BAKED_MAIL_PORT);
export const getMailSecure = () => pick(process.env.MAIL_SECURE, BAKED_MAIL_SECURE);
export const getSmsApiKey  = () => pick(process.env.SMS_API_KEY, BAKED_SMS_API_KEY);
export const getSmsSender  = () => pick(process.env.SMS_SENDER,  BAKED_SMS_SENDER);
export const getSmsSandbox = () => pick(process.env.SMS_SANDBOX, BAKED_SMS_SANDBOX);

/** Diagnostic — used by the admin panel to render the green/amber
 *  delivery banner. SMTP needs host + user + pass at minimum;
 *  MAIL_FROM falls back to MAIL_USER inside the sender. */
export function detectNotificationDelivery() {
  const smtpConfigured = !!(getMailHost() && getMailUser() && getMailPass());
  const smsConfigured  = !!getSmsApiKey();
  return { smtpConfigured, smsConfigured };
}
