// v0.5.53 — Effective cloud key resolver for the renderer.
//
// HISTORY
// -------
// v0.5.52 read keys from process.env.NEXT_PUBLIC_SCRIPTURELIVE_*
// inlined via next.config.ts `env`. That worked in CI but failed
// silently when next dev/build started before the env vars existed
// in the parent shell — the bundle baked empty strings and the
// shipped .exe greeted users with "No OpenAI key configured".
//
// v0.5.53 reads from `keys.baked.ts`, a tiny generated TS file
// containing literal string constants. The file is generated by
// `scripts/inject-keys.mjs` (run as predev / prebuild and inside
// BUILD.bat). Because the keys are PLAIN SOURCE CODE, Webpack /
// Turbopack inline them deterministically — no env-var timing
// games, no NEXT_PUBLIC_ propagation quirks.
//
// FALLBACK CHAIN AT RUNTIME
// -------------------------
//   1. Admin override fetched from /api/license/admin/keys
//   2. Baked default from keys.baked.ts (operator's keys)
//   3. null  -> caller surfaces a generic "contact administrator"
//
// SECURITY NOTE
// -------------
// keys.baked.ts is .gitignored. Source-zip packager includes it
// explicitly so the operator's build always has the keys, but
// GitHub never sees them (avoids OpenAI / Deepgram secret-scanner
// auto-revocation).

import { BAKED_OPENAI_KEY, BAKED_DEEPGRAM_KEY } from './keys.baked'

const BAKED_OPENAI = (BAKED_OPENAI_KEY || '').trim()
const BAKED_DEEPGRAM = (BAKED_DEEPGRAM_KEY || '').trim()

let overrideOpenAI: string | null = null
let overrideDeepgram: string | null = null
let bootstrapPromise: Promise<void> | null = null

interface KeyOverridesResponse {
  openai?: string | null
  deepgram?: string | null
}

async function fetchOverrides(): Promise<void> {
  if (typeof fetch === 'undefined') return
  try {
    const r = await fetch('/api/license/admin/keys', { cache: 'no-store' })
    if (!r.ok) return
    const j = (await r.json()) as KeyOverridesResponse
    overrideOpenAI = (j.openai ?? '').trim() || null
    overrideDeepgram = (j.deepgram ?? '').trim() || null
  } catch {
    /* ignore — falls back to baked */
  }
}

/** Kick off the override fetch once. Safe to call from many places. */
export function bootstrapRuntimeKeys(): Promise<void> {
  if (!bootstrapPromise) bootstrapPromise = fetchOverrides()
  return bootstrapPromise
}

/** Force a re-fetch (call after admin saves new override values). */
export async function refreshKeyOverrides(): Promise<void> {
  bootstrapPromise = fetchOverrides()
  return bootstrapPromise
}

export function getOpenAIKey(): string | null {
  if (overrideOpenAI) return overrideOpenAI
  return BAKED_OPENAI || null
}

export function getDeepgramKey(): string | null {
  if (overrideDeepgram) return overrideDeepgram
  return BAKED_DEEPGRAM || null
}

/** Diagnostic — used by Settings UI to render "managed by admin" badges. */
export function getKeyStatus(): {
  openai: { source: 'override' | 'baked' | 'missing' }
  deepgram: { source: 'override' | 'baked' | 'missing' }
} {
  return {
    openai: {
      source: overrideOpenAI ? 'override' : BAKED_OPENAI ? 'baked' : 'missing',
    },
    deepgram: {
      source: overrideDeepgram
        ? 'override'
        : BAKED_DEEPGRAM
        ? 'baked'
        : 'missing',
    },
  }
}
